version: '3.7'
services:
  # postgres:
  #   image: postgres:13
  #   container_name: postgres_db
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_DB: poll_db
  #     POSTGRES_USER: poll_user
  #     POSTGRES_PASSWORD: poll_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  # postgres_data:
  pgadmin-data:
